---
title: "DATA 605 - Assignment 3 - Eigenvalues & Eigenvectors"
author: "Christopher Martin"
date: "September 13, 2016"
output:
  html_document:
    fig_caption: yes
    force_captions: yes
    highlight: pygments
    number_sections: yes
    theme: united
    toc: no
  pdf_document:
    fig_caption: yes
    highlight: pygments
    latex_engine: xelatex
    number_sections: yes
    toc: no
title2: Eigenvalues & Eigenvectors
---

# Problem Set 1

a. What is the rank of the matrix A?
A = [1, 2, 3, 4 / -1, 0, 1, 3 / 0, 1, -2, 1 / 5, 4, -2, -3]

A is rank 4


b. Given an **mxn** matrix where **m > n**, what can be the maximum rank? The minimum rank, assuming that the matrix is non-zero?

The rank can be no greater than the numbers of rows (n), and the minimum rank is 1.


c. What is the rank of matrix B?
B = [1, 2, 1, / 3, 6, 3 / 2, 4, 2]

Since R2=(R1)(3) and R3=(R1)(2), its rank is 1 because we are left with [1, 2, 1 / 0, 0, 0, / 0, 0, 0].


# Problem Set 2

Compute the eigenvalues and eigenvectors of the matrix A. You'll need to show your work.  You'll need to write out the characteristic polynomial and show your solution.
A = [1, 2, 3 / 0, 4, 5 / 0, 0, 6]

det(lambda * I(n) - A) = 0

det([lambda, 0, 0 / 0, lambda, 0 / 0, 0, lambda] - [1, 2, 3 / 0, 4, 5 / 0, 0, 6]) = 0

det([lambda - 1, -2, -3 / 0, lambda - 4, -5 / 0, 0, lambda - 6]) = 0

det = (lambda - 1)(lambda - 4)(lambda - 6) = 0
*possible eigenvaules = 1, 4, 6*

0 = (lambda*I(n) - A) * eigenvector(v)

*lambda = 1*
[0, -2, -3 / 0, -3, -5 / 0, 0, -5] * [v1, v2, v3] = 0
v1 = 0

R3 = R2 - R3 and R2 = R1 - R2 =
[0, -2, -3 / 0, 1, 2 / 0, 0, 0] * [0, v2, v3] = 0

R2 = R1 * (-3/2) - R2 =
[0, (-3/2)(2) - (-3), (-3/2)(-3) - (-5)] =
[0, -2, -3 / 0, 0, (1/2) / 0, 0, 0] * [0, v2, (1/2)] = 0

R1 = R1 / -2 =
[0, -2/-2, -3/-2] =
[0, 1, (3/2) / 0, 0, (1/2) / 0, 0, 0] * v = 0

**E(lambda=1) = span(a[0, 1, (1/2)])**


*lambda = 4*
[3, -2, -3 / 0, 0, -5 / 0, 0, -1] * [v1, v2, v3] = 0

R3 = 5*R2 - R3 and R2 = R1(5/3) - R2 =
[3, -2, -3 / 0, 0, (5/3)(3)-(-5) / 0, 0, (5)(-1)-(-5)] = 0
[3, -2, -3 / 0, 0, 0 / 0, 0, 0] * [v1, v2, v3] = 0

3(v1) - 2(v2) - 3(v3) = 0
if v1 = 1, 3 - 2(v2) - 3(v3) = 0, v2 = 0, v3 = -1
v2 must = 0 since v1 and v3 will automatically cancel out

**E(lambda = 3) = span(a[1,0,-1])**


*lambda = 6*
[5, -2, -3 / 0, 2, -5 / 0, 0, 0] * v = 0

R2 = (-1)(R1) - R2 = 
[5, -2, -3 / 0, 0, 8 / 0, 0, 0]

R2 = (8/3)(R1) - R2 =
[5, -2, -3 / 0, 0, 0 / 0, 0, 0] * [v1, v2, v3] = 0

5(v1) - 2(v2) - 3(v3) = 0
if v1 = 1, then v2 = 1, v3 = 1
if any v = 1, then all other v = 1

**E(lambda = 3) = span(a[1,1,1])**