---
title: "DATA 605 - Assignment 2 - Trace, Determinant, Factorization of Matrices"
author: "Christopher Martin"
date: "September 6, 2016"
output:
  html_document:
    fig_caption: yes
    force_captions: yes
    highlight: pygments
    number_sections: yes
    theme: united
    toc: no
  pdf_document:
    fig_caption: yes
    highlight: pygments
    latex_engine: xelatex
    number_sections: yes
    toc: no
title2: Trace, Determinant, Factorization of Matrices
---

# Problem Set 1

(1)  Show that:

$A^T * A not = A * A^T$

in general.

-  Generally, due to the order of multiplication in that also applies when matrix A * matrix B does not equal matrix B * matrix A, matrix A transposed * matrix A does not equal matrix A * matrix A transposed. The most simple situation is when matrix A has n rows and m columns and m does not equal n, then the resulting matrix will have m(2) columns and n(2) rows; the opposite situation (the matrix is transposed) will result in a different number of columns and rows. Example:

A = [-1, 1, 0 / 0, -1, 1] and A^T = [-1, 0 / 1, -1, 0, 1]

$A * A^T =$ [2, -1 / -1, 2] and $A^T * A =$ [1, -1, 0 / -1, 2, -1 / 0, -1, 1]


(2)  For a special type of square matrix **A**, we get 

$A^T * A = A * A^T$ 

Under what conditions could this be true?  (Hint:  The Identity matrix **I** is an example of such a matrix).

-  A symmetric matrix with diagonal 1's and m columns = n rows would make this true.

# Problem Set 2

Matrix factorization is a very important problem.  There are supercomputers built just to  do  matrix  factorizations.   Every  second  you  are  on  an  airplane,  matrices  are  being factorized.  Radars that track  ights use a technique called Kalman Filtering.  At the heart of Kalman Filtering is a Matrix Factorization operation.  Kalman Filters are solving linear systems of equations when they track your flight using radars.

Write  an  R  function  to  factorize  a  square  matrix  A  into  LU  or  LDU,  whichever  you prefer. You don't have to worry about permuting rows of A and you can assume that A is less than  5x5,  if  you  need  to  hard-code  any  variables  in  your  code.

- Factorization:

$A = L * U$

For a 3x3 matrix:

```{r}

factorization <- function(A){
  e21 <- matrix(c(1,-A[2,1]/A[1,1],0,0,1,0,0,0,1), nrow=3)
  matrixY <- e21 %*% A
  
  e31 <- matrix(c(1,0,-matrixY[3,1]/matrixY[1,1],0,1,0,0,0,1),nrow=3) 
  matrixY <- e31 %*% matrixY

  e32 <- matrix(c(1,0,0,0,1,-matrixY[3,2]/matrixY[2,2],0,0,1),nrow=3)
  U <- e32 %*% matrixY

  L <- solve(e21) %*% solve(e31) %*% solve(e32)
  
  A == L %*% U
}

A <- matrix(c(1,2,3,1,1,1,2,0,1),nrow=3)

factorization(A)
```
